website/music/urls.py
from django.conf.urls import url
from . import views

#$ sign means go to the default home page of each app

# app_name deifnes the unique name for this music app. For. if you have detail view for two or more apps, browser will get con
#fused so in order to make it connect with music we use app name
app_name = 'music'

# urlpatterns = [
#     # /music/
#     url(r'^$', views.index, name='index'),
#
#     # /music/album_id/
#     #(? P<album_id> isrepresenting 712 as a one word and we can use album_id to save a id), 0-9 is a range for id's
#     url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
#
#     # url without view,just an action
#     url(r'^(?P<album_id>[0-9]+)/favorites/$', views.favorite, name='favorite'),
# ]


urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/album_id/
    #(? P<album_id> isrepresenting 712 as a one word and we can use album_id to save a id), 0-9 is a range for id's
   # url(r'^(?P<album_id>[0-9]+)/$', views.IndexView.as_view, name='detail'),

    # url without view,just an action, pk is primary key.
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

# /music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

# /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

website/website/urls.py
# use include to use external files
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from django.db import models
# Create your models here.
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


# this does the redirect when we submit the add album
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})



    def __str__(self):
            return self.album_title + ' - ' + self.artist

#album is a foriegn key in song

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title
# after you create the classes , go to the terminal inside website and run - python manage.py makemigrations music
# then run - python manage.py migrate : this will run the migrations and will create tables in the database

website/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

# widget is use to save the password as a password field in the DB
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

website/music/views.py
from django.shortcuts import render
from django.views import generic
from .models import Album
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
#please check the commented code too


#Please check the commented code- it was used to display the views before we star

#
# # Create your views here.
# # in index view, we are showing the view page using album id.
# def index(request):
#     all_albums = Album.objects.all()
#        # context is a dictionary and use to send value from view to templates
#     context = {'all_albums': all_albums}
#     # render has built in httpresponse
#     return render(request,'music/index.html',context)
#
#
# # use 404 object instead of try except block
# def detail(request, album_id):
#     all_albums = Album.objects.all()
#     album = get_object_or_404(Album, pk=album_id)
#
#     context = {'all_albums': all_albums,
#                    'album': album}
#     return render(request,'music/detail.html', context)
#
#
# #old way of doing using try except
# def detail_copy(request, album_id):
#     all_albums = Album.objects.all()
#
#     # if album id does not exist then send http404 not found error
#     try:
#         album = Album.objects.get(id=album_id)
#         context = {'all_albums': all_albums,
#                    'album': album}
#     except Album.DoesNotExist:
#         raise Http404("Album does not exist")
#     return render(request,'music/detail.html', context)
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except(KeyError, Song.DoestNotExist):
#         return render(request, 'music/detail.html', {
#             'album': album,
#             'error_message': "You did not select a valid song",
#
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album': album})


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    #used to represent the object
    context_object_name = 'all_albums'

#querying the database to get all the albums
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    # this means which table details we need to display
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    #what kind of object you need to save in DB, in this case it is album
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    #what kind of object you need to update in DB, in this case it is album
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    #what kind of object you need to delete in DB, in this case it is album
    model = Album
    # after delete where to redirect
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

#if your method is get in form, use this, blank form
    def get(self, request):
        form = self.form_class(None)
        #returning a blank form
        return render(request, self.template_name, {'form': form})

    # process form data if the method is post
    def post(self, request):
        form = self.form_class(request.POST)


#validating the form before saving it to the database
        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized the data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #if u need to change the password
            user.set_password(password)
            user.save()

            #Authenticate user
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

                #if user could not login , he will redirect to this form
                return render(request, self.template_name, {'form': form})

website/music/templates/music/album_form.html
 {% extends 'music/base.html' %}
 {% block title %} Add a New Album {% endblock %}
 {% block albums_active %}active{% endblock %}

 {% block body %}
 <div class="container-fluid">

     <div class="row">
         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         <!--making generic form-->
                         {% include 'music/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>

                             </div>
                         </div>


                     </form>

                 </div>

             </div>

         </div>

     </div>

 </div>
 {% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    <!---Load the path to your static files -->
    {% load staticfiles %}
    <!--Load bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--google fonts-->
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <!--jquery and bootstrap jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header-->
        <div class="navbar-header">
            <!--This is button, it will appear when you clollapse the webpage, so that you can still see the navbar items-->
            <button type="button" class="navbar-toggle" data-toggle ="collapse" data-target="#topNavBar">
                <!--creating hamburger icon-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--logo-->
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!--Items-->

    <div class="collapse navbar-collapse" id="topNavBar">

        <ul class="nav navbar-nav">
            <li class="active">
                <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                </a>
            </li>
                        <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                </a>
            </li>
        </ul>
        <!--search box on navbar-->
        <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="{% url 'music:album-add' %}">
                   <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album

                </a>

            </li>
             <li class="">
                <a href="#">
                   <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout

                </a>

            </li>

        </ul>
    </div>


    </div>
</nav>
<!--this we defines a place in template to put the body code-->
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
 {% extends 'music/base.html' %}
 <!--adding custom title for each page, you use block to write this code-->
 {% block title %}Album Details{% endblock %}
 {% block body %}
<img src="{{album.album_logo}}" style="width: 250px;">
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>
<!--
<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{song.file_type}}</li>
    {% endfor %}
</ul>

<ul>
    {% for album in all_albums %}
    <li>{{ album.album_title }}</li>
    {% endfor %}
</ul>-->
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{% url 'music:detail' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter}}" name="song" value="{{song.id}}">
        <label for ="song{{ forloop.counter}}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png">
            {% endif %}
        </label><br>
    {% endfor %}

    <input type="submit" value="Favorite">
</form>
 {% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>

        </div>
        <!--these are the label for inputs-->
<label class="control-label col-sm-2">{{field.label_tag}}</label>
        <!--this is the input for the fields-->
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums's Name</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}

website/music/templates/music/registration_form.html
 {% extends 'music/base.html' %}
 {% block title %} Register {% endblock %}


 {% block body %}
 <div class="container-fluid">

     <div class="row">
         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <h3>Create a New Account</h3>
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         <!--making generic form-->
                         {% include 'music/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>

                             </div>
                         </div>


                     </form>

                 </div>

             </div>

         </div>

     </div>

 </div>
 {% endblock %}